ktor:
    application:
        modules:
            - com.eros.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  secret: ${JWT_SECRET}
  domain: ${JWT_DOMAIN:https://jwt-provider-domain/}
  audience: ${JWT_AUDIENCE:jwt-audience}
  realm: ${JWT_REALM:ktor sample app}
database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:eros}
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:postgres}
  poolSize: ${DB_POOL_SIZE:10}
  maxLifetime: ${DB_MAX_LIFETIME:600000}
  connectionTimeout: ${DB_CONNECTION_TIMEOUT:30000}
